// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXMD63NaOlOiIW7yfrNjJbioO_c-bQATs',
    appId: '1:615738260899:web:c975765fd09718f0272e16',
    messagingSenderId: '615738260899',
    projectId: 'seerooms-63da8',
    authDomain: 'seerooms-63da8.firebaseapp.com',
    storageBucket: 'seerooms-63da8.appspot.com',
    measurementId: 'G-X361H16W90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7ZDzkPLEjuyEDqZYQlTg6rB1W8gwQayI',
    appId: '1:615738260899:android:48450b2f9291143a272e16',
    messagingSenderId: '615738260899',
    projectId: 'seerooms-63da8',
    storageBucket: 'seerooms-63da8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD8C5LMzOS9MCaS1pn7LfKC7JWCg_sXvM',
    appId: '1:615738260899:ios:c560e1700958e88a272e16',
    messagingSenderId: '615738260899',
    projectId: 'seerooms-63da8',
    storageBucket: 'seerooms-63da8.appspot.com',
    iosClientId: '615738260899-qo1qr8e9ol3j0n3dm1uv6q1fvosr8n93.apps.googleusercontent.com',
    iosBundleId: 'com.example.seerooms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD8C5LMzOS9MCaS1pn7LfKC7JWCg_sXvM',
    appId: '1:615738260899:ios:c560e1700958e88a272e16',
    messagingSenderId: '615738260899',
    projectId: 'seerooms-63da8',
    storageBucket: 'seerooms-63da8.appspot.com',
    iosClientId: '615738260899-qo1qr8e9ol3j0n3dm1uv6q1fvosr8n93.apps.googleusercontent.com',
    iosBundleId: 'com.example.seerooms',
  );
}
